//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_drops_H
#define METASPRITE_drops_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define drops_TILE_ORIGIN 0
#define drops_TILE_W 8
#define drops_TILE_H 8
#define drops_WIDTH 80
#define drops_HEIGHT 8
#define drops_TILE_COUNT 10

BANKREF_EXTERN(drops)

extern const uint8_t drops_tiles[160];

#endif
