//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_floor_H
#define METASPRITE_floor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define floor_TILE_ORIGIN 0
#define floor_TILE_W 8
#define floor_TILE_H 8
#define floor_WIDTH 88
#define floor_HEIGHT 8
#define floor_TILE_COUNT 11

BANKREF_EXTERN(floor)

extern const uint8_t floor_tiles[176];

#endif
