//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hud_H
#define METASPRITE_hud_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hud_TILE_ORIGIN 0
#define hud_TILE_W 8
#define hud_TILE_H 8
#define hud_WIDTH 24
#define hud_HEIGHT 8
#define hud_TILE_COUNT 3

BANKREF_EXTERN(hud)

extern const uint8_t hud_tiles[48];

#endif
