//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_lamp_H
#define METASPRITE_lamp_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define lamp_TILE_ORIGIN 0
#define lamp_TILE_W 8
#define lamp_TILE_H 16
#define lamp_WIDTH 80
#define lamp_HEIGHT 16
#define lamp_TILE_COUNT 20

BANKREF_EXTERN(lamp)

extern const uint8_t lamp_tiles[320];

#endif
