//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_logo_H
#define METASPRITE_logo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define logo_TILE_ORIGIN 0
#define logo_TILE_W 8
#define logo_TILE_H 16
#define logo_WIDTH 248
#define logo_HEIGHT 16
#define logo_TILE_COUNT 62

BANKREF_EXTERN(logo)

extern const uint8_t logo_tiles[992];

#endif
