//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_player_H
#define METASPRITE_player_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_TILE_ORIGIN 0
#define player_TILE_W 8
#define player_TILE_H 16
#define player_WIDTH 56
#define player_HEIGHT 16
#define player_TILE_COUNT 14

BANKREF_EXTERN(player)

extern const uint8_t player_tiles[224];

#endif
