//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_skyline_H
#define METASPRITE_skyline_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define skyline_TILE_ORIGIN 0
#define skyline_TILE_W 8
#define skyline_TILE_H 16
#define skyline_WIDTH 168
#define skyline_HEIGHT 16
#define skyline_TILE_COUNT 42

BANKREF_EXTERN(skyline)

extern const uint8_t skyline_tiles[672];

#endif
