//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_right_1_H
#define METASPRITE_tree_right_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_right_1_TILE_ORIGIN 0
#define tree_right_1_TILE_W 8
#define tree_right_1_TILE_H 8
#define tree_right_1_WIDTH 32
#define tree_right_1_HEIGHT 8
#define tree_right_1_TILE_COUNT 4

BANKREF_EXTERN(tree_right_1)

extern const uint8_t tree_right_1_tiles[64];

#endif
