//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_left_3_H
#define METASPRITE_tree_left_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_left_3_TILE_ORIGIN 0
#define tree_left_3_TILE_W 8
#define tree_left_3_TILE_H 8
#define tree_left_3_WIDTH 32
#define tree_left_3_HEIGHT 8
#define tree_left_3_TILE_COUNT 4

BANKREF_EXTERN(tree_left_3)

extern const uint8_t tree_left_3_tiles[64];

#endif
