//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_solids_H
#define METASPRITE_tree_solids_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_solids_TILE_ORIGIN 0
#define tree_solids_TILE_W 8
#define tree_solids_TILE_H 8
#define tree_solids_WIDTH 16
#define tree_solids_HEIGHT 8
#define tree_solids_TILE_COUNT 2

BANKREF_EXTERN(tree_solids)

extern const uint8_t tree_solids_tiles[32];

#endif
