//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_right_3_H
#define METASPRITE_tree_right_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_right_3_TILE_ORIGIN 0
#define tree_right_3_TILE_W 8
#define tree_right_3_TILE_H 8
#define tree_right_3_WIDTH 40
#define tree_right_3_HEIGHT 8
#define tree_right_3_TILE_COUNT 5

BANKREF_EXTERN(tree_right_3)

extern const uint8_t tree_right_3_tiles[80];

#endif
