//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_right_2_H
#define METASPRITE_tree_right_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_right_2_TILE_ORIGIN 0
#define tree_right_2_TILE_W 8
#define tree_right_2_TILE_H 8
#define tree_right_2_WIDTH 72
#define tree_right_2_HEIGHT 8
#define tree_right_2_TILE_COUNT 9

BANKREF_EXTERN(tree_right_2)

extern const uint8_t tree_right_2_tiles[144];

#endif
