//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_left_1_H
#define METASPRITE_tree_left_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_left_1_TILE_ORIGIN 0
#define tree_left_1_TILE_W 8
#define tree_left_1_TILE_H 8
#define tree_left_1_WIDTH 48
#define tree_left_1_HEIGHT 8
#define tree_left_1_TILE_COUNT 6

BANKREF_EXTERN(tree_left_1)

extern const uint8_t tree_left_1_tiles[96];

#endif
