//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tree_left_2_H
#define METASPRITE_tree_left_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tree_left_2_TILE_ORIGIN 0
#define tree_left_2_TILE_W 8
#define tree_left_2_TILE_H 8
#define tree_left_2_WIDTH 80
#define tree_left_2_HEIGHT 8
#define tree_left_2_TILE_COUNT 10

BANKREF_EXTERN(tree_left_2)

extern const uint8_t tree_left_2_tiles[160];

#endif
